### ISSUE TITLE
Cannot import my maFiles

### ISSUE THREAD

**Issue by kenteg** [achiez/NebulaAuth-Steam-Desktop-Authenticator-by-Achies#3]
Error when i tried import my files from old SDA
log:
[log.log](https://github.com/user-attachments/files/17346411/log.log)

**Comment by achiez** [comment]
It's seems your mafiles are encrypted. 
1. Open your old SDA Application
2. Click on "Set Encryption"
![image](https://github.com/user-attachments/assets/72c2f355-b88b-4b96-8dc8-540be302a11b)
3. Enter old password if required
4. Leave new password blank and proceed
5. Now your mafiles are decrypted and you can import them in Nebula

**Comment by kenteg** [comment]
Now its works, thank you!
